### ISSUE TITLE
Official link validator

### ISSUE THREAD

**Issue by edzio27** [shortstuffsushi/Universal-Link-Validator#6]
There is an official link validator for app indexing:
https://search.developer.apple.com/appsearch-validation-tool/

is it the same as in repo?

**Comment by shortstuffsushi** [comment]
Hey, thanks for noticing. That tool is similar to mine, and provides a good amount of functionality (including other stuff like the meta items on the page) -- it's really nice. The only thing it doesn't really offer is the IPA upload, which checks all your domains at once. I haven't tested extensively, but it also probably doesn't have step by step error instructions. I have actually mentioned it in the readme for this project -- it's probably good enough, but since I'm not paying anything to host this currently, and I still get on order of 4K hits per week, I'm going to leave it up for now.
